//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TilemapJP {

public enum ThinPlateSplineInterType {
  THINPLATE_SPLINE_ZERO_POINTS,
  THINPLATE_SPLINE_ONE_POINT,
  THINPLATE_SPLINE_TWO_POINTS,
  THINPLATE_SPLINE_ONE_DIMENSIONAL,
  THINPLATE_SPLINE_FULL,
  THINPLATE_SPLINE_POINT_WAS_ADDED,
  THINPLATE_SPLINE_POINT_WAS_DELETED
}

}
