//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TilemapJP {

public class ThinPlateSplineConst {
  public static readonly int THINPLATE_SPLINE_MAX_VARS = ThinPlateSplineConstPINVOKE.THINPLATE_SPLINE_MAX_VARS_get();
}

}
